/**
 * The cluster configuration an operator reviews and applies (ADR 0072): the DRBD resource and
 * the Pacemaker commands. Fencing parameters belong to the site (addresses, credentials), so the
 * plan names the agent and leaves those values for the operator; nothing here is applied.
 */
export interface ClusterNode {
  readonly name: string;
  readonly address: string;
  /** DRBD node id, 0-based, unique in the resource. */
  readonly id: number;
}

export interface ClusterPlanInput {
  readonly profile: 'ha-2' | 'ha-3';
  readonly resource: string;
  readonly root: string;
  /** Backing disk of the volume on every data node, e.g. /dev/vg0/arkvory. */
  readonly disk: string;
  readonly minor: number;
  readonly port: number;
  readonly filesystem: 'xfs' | 'ext4';
  readonly nodes: readonly ClusterNode[];
  /** ha-2: the diskless tiebreaker and corosync-qnetd host; absent in ha-3. */
  readonly witness?: ClusterNode;
  readonly fenceAgent: string;
  readonly virtualIp: string;
  readonly netmask: number;
}

const NAME = /^[a-z][a-z0-9-]{0,62}$/;
const ADDRESS = /^[0-9a-fA-F.:]{3,45}$/;
const AGENT = /^fence_[a-z0-9_]{2,40}$/;

export function checkPlan(input: ClusterPlanInput): void {
  const data = input.profile === 'ha-2' ? 2 : 3;
  if (input.nodes.length !== data)
    throw new Error(`${input.profile} needs exactly ${String(data)} data nodes`);
  if (input.profile === 'ha-2' && !input.witness)
    throw new Error('ha-2 needs a witness: two votes cannot tell a failure from a partition');
  if (input.profile === 'ha-3' && input.witness)
    throw new Error('ha-3 decides by majority of its three data nodes; it takes no witness');
  const all = [...input.nodes, ...(input.witness ? [input.witness] : [])];
  if (new Set(all.map((node) => node.name)).size !== all.length)
    throw new Error('Node names repeat');
  if (new Set(all.map((node) => node.id)).size !== all.length) throw new Error('Node ids repeat');
  for (const node of all)
    if (!NAME.test(node.name) || !ADDRESS.test(node.address) || node.id < 0 || node.id > 31)
      throw new Error(`Invalid node ${node.name}`);
  if (!NAME.test(input.resource)) throw new Error('Invalid resource name');
  if (!/^\/dev\/[A-Za-z0-9/_.-]+$/.test(input.disk)) throw new Error('Invalid backing disk');
  if (!input.root.startsWith('/') || /[\s"'$`\\]/.test(input.root))
    throw new Error('Invalid installation root');
  if (!AGENT.test(input.fenceAgent))
    throw new Error('A fence agent (fence_ipmilan, fence_redfish, fence_pve…) is required');
  if (!ADDRESS.test(input.virtualIp) || input.netmask < 1 || input.netmask > 128)
    throw new Error('Invalid virtual address');
  if (input.minor < 0 || input.minor > 1048575 || input.port < 1024 || input.port > 65535)
    throw new Error('Invalid DRBD minor or port');
}

/** The DRBD 9 resource: protocol C, fencing through Pacemaker, quorum by majority. */
export function drbdResource(input: ClusterPlanInput): string {
  checkPlan(input);
  const host = (node: ClusterNode, disk: string) =>
    `  on ${node.name} {\n    node-id ${String(node.id)};\n    address ${node.address}:${String(input.port)};\n    disk ${disk};\n    meta-disk internal;\n  }`;
  return [
    `# Arkvory HA volume (ADR 0072, profile ${input.profile}). Generated by arkvory cluster-plan.`,
    `resource ${input.resource} {`,
    `  device minor ${String(input.minor)};`,
    '  options {',
    // Without a quorum partition, IO fails at once: Pacemaker fences or moves the node instead
    // of a stale side writing alone.
    '    quorum majority;',
    '    on-no-quorum io-error;',
    '  }',
    '  net {',
    '    protocol C;',
    '    fencing resource-and-stonith;',
    '  }',
    '  handlers {',
    '    fence-peer "/usr/lib/drbd/crm-fence-peer.9.sh";',
    '    unfence-peer "/usr/lib/drbd/crm-unfence-peer.9.sh";',
    '  }',
    ...input.nodes.map((node) => host(node, input.disk)),
    ...(input.witness ? [host(input.witness, 'none')] : []),
    '  connection-mesh {',
    `    hosts ${[...input.nodes, ...(input.witness ? [input.witness] : [])].map((node) => node.name).join(' ')};`,
    '  }',
    '}',
    '',
  ].join('\n');
}

/**
 * Pacemaker: mandatory fencing, the promotable DRBD clone and one group started in order on its
 * primary — filesystem, PostgreSQL, the replica helper, Arkvory, the updater, the address.
 */
export function pacemakerCommands(input: ClusterPlanInput): string {
  checkPlan(input);
  const r = input.resource;
  const lines = [
    '#!/bin/sh',
    `# Arkvory HA (ADR 0072, profile ${input.profile}). Generated by arkvory cluster-plan.`,
    '# Review before running on ONE node of a configured, started cluster. Fill every <...>.',
    ...(input.witness
      ? [
          `# The witness ${input.witness.name} is not a Pacemaker node: it runs corosync-qnetd and the`,
          '# diskless DRBD tiebreaker (drbdadm up on boot), nothing of Arkvory.',
        ]
      : []),
    'set -eu',
    'pcs property set stonith-enabled=true',
    'pcs property set no-quorum-policy=stop',
    ...input.nodes.map(
      (node) =>
        `pcs stonith create fence-${node.name} ${input.fenceAgent} pcmk_host_list=${node.name} <agent parameters: address, login, password file>`,
    ),
    ...(input.witness
      ? [`pcs quorum device add model net host=${input.witness.address} algorithm=ffsplit`]
      : []),
    `pcs resource create ${r}-drbd ocf:linbit:drbd drbd_resource=${r} op monitor interval=15s role=Promoted op monitor interval=29s role=Unpromoted promotable promoted-max=1 promoted-node-max=1 clone-max=${String(input.nodes.length)} clone-node-max=1 notify=true`,
    `pcs resource create ${r}-fs ocf:heartbeat:Filesystem device=/dev/drbd${String(input.minor)} directory=${input.root} fstype=${input.filesystem} --group ${r}`,
    `pcs resource create ${r}-database systemd:arkvory-database op monitor interval=15s --group ${r}`,
    `pcs resource create ${r}-replica systemd:arkvory-replica op monitor interval=15s --group ${r}`,
    ...['api', 'worker', 'backup'].map(
      (role) =>
        `pcs resource create ${r}-${role} systemd:arkvory-${role} op monitor interval=15s op stop timeout=150s --group ${r}`,
    ),
    `pcs resource create ${r}-update systemd:arkvory-update.timer --group ${r}`,
    `pcs resource create ${r}-ip ocf:heartbeat:IPaddr2 ip=${input.virtualIp} cidr_netmask=${String(input.netmask)} op monitor interval=10s --group ${r}`,
    `pcs constraint colocation add ${r} with Promoted ${r}-drbd-clone INFINITY`,
    `pcs constraint order promote ${r}-drbd-clone then start ${r}`,
    `pcs resource defaults update resource-stickiness=200`,
    '',
  ];
  return lines.join('\n');
}
