import { readFile, unlink } from 'node:fs/promises';
import { join } from 'node:path';
import { atomicText, jsonFile } from './files.js';
import type { ComposeCall } from './backup-service.js';
import type { Installation } from './model.js';
import { command, isUnconfirmedTermination } from './process.js';
import { runtimeEnvironment } from './runtime.js';
import { unsafePath } from './vault-location.js';

/** Where the Compose backup container sees the bind-mounted host vault. */
export const containerVault = '/srv/arkvory-vault';
/** Compose override with the vault bind mount; present only while a vault is configured. */
export const vaultOverrideFile = 'config/compose.vault.yml';

/**
 * Bind mount of the host vault for the backup service and its one-shot ownership fix. No host
 * path is created: a missing directory fails the container instead of writing elsewhere.
 */
export function vaultOverride(source: string): string {
  if (unsafePath(source)) throw new Error('Unsupported vault path');
  const mount = [
    '      - type: bind',
    `        source: '${source}'`,
    `        target: ${containerVault}`,
    '        bind:',
    '          create_host_path: false',
  ];
  return [
    '# Generated by arkvory configure --backup-vault. Remove with --backup-vault-off.',
    'services:',
    '  backup:',
    '    volumes:',
    ...mount,
    '  vault-owner:',
    '    volumes:',
    ...mount,
    '',
  ].join('\n');
}

const missing = (error: unknown) =>
  error instanceof Error && 'code' in error && error.code === 'ENOENT';

async function optionalText(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf8');
  } catch (error) {
    if (missing(error)) return null;
    throw error;
  }
}

async function remove(path: string): Promise<void> {
  await unlink(path).catch((error: unknown) => {
    if (!missing(error)) throw error;
  });
}

/**
 * Gives the backup service exactly one vault, in the way of each supervisor: a systemd drop-in
 * that opens the read-only sandbox for the vault (owner arkvory, 0700), an ACL for LocalService
 * on Windows, or a Compose bind mount owned by the container user. Grants are never revoked:
 * the vault itself stays untouched when another vault is configured or the vault is turned off.
 */
export class VaultAccess {
  constructor(
    private readonly root: string,
    private readonly state: Installation,
    private readonly compose: ComposeCall,
  ) {}

  private script(name: string): string {
    return join(this.root, 'releases', this.state.current.version, 'deploy', name);
  }

  private async configuredVault(): Promise<string | null> {
    const env = runtimeEnvironment(await jsonFile(join(this.root, 'config/runtime.json')));
    return env['ARKVORY_BACKUP_VAULT'] ?? null;
  }

  private linux(vault: string | null): Promise<void> {
    return command('bash', [this.script('backup-vault-linux.sh'), this.root, vault ?? '-']);
  }

  private windows(vault: string, engineUser: boolean): Promise<void> {
    return command('powershell.exe', [
      '-NoProfile',
      '-NonInteractive',
      '-ExecutionPolicy',
      'Bypass',
      '-File',
      this.script('backup-vault-windows.ps1'),
      '-Vault',
      vault,
      ...(engineUser ? ['-EngineUser'] : []),
    ]);
  }

  /** How to return to the current exposure; captured before anything changes. */
  private async snapshot(): Promise<() => Promise<void>> {
    if (this.state.mode === 'systemd') {
      const previous = await this.configuredVault();
      return () => this.linux(previous);
    }
    if (this.state.mode === 'windows') return () => Promise.resolve();
    const path = join(this.root, vaultOverrideFile);
    const previous = await optionalText(path);
    return () => (previous === null ? remove(path) : atomicText(path, previous, 0o600));
  }

  private async apply(vault: string | null): Promise<void> {
    if (this.state.mode === 'systemd') return this.linux(vault);
    if (this.state.mode === 'windows') {
      if (vault) await this.windows(vault, false);
      return;
    }
    const path = join(this.root, vaultOverrideFile);
    if (vault === null) return remove(path);
    await atomicText(path, vaultOverride(vault), 0o600);
    // Docker Desktop reads bind mounts with its user's token (ADR 0050).
    if (process.platform === 'win32') await this.windows(vault, true);
    await this.compose(this.state.current, ['run', '--rm', '--no-deps', 'vault-owner']);
  }

  /**
   * Opens `vault` (null: none) for the backup service and returns the way back. A step that
   * fails halfway (drop-in written, reload failed) is undone here, before the error propagates.
   */
  async open(vault: string | null): Promise<() => Promise<void>> {
    const restore = await this.snapshot();
    try {
      await this.apply(vault);
    } catch (error) {
      // A command that may still run is never raced; the operation lock stays for the operator.
      if (!isUnconfirmedTermination(error)) await restore().catch(() => undefined);
      throw error;
    }
    return restore;
  }

  /** `vault init` of this release's backup CLI with the installation's runtime environment. */
  async initialize(vault: string): Promise<void> {
    if (this.state.mode === 'compose')
      await this.compose(this.state.current, [
        'run',
        '--rm',
        '--no-deps',
        'backup',
        'vault-init',
        containerVault,
      ]);
    else
      await command(process.execPath, [
        this.script('launcher.mjs'),
        this.root,
        'vault-init',
        vault,
      ]);
  }
}
